MDW\RosantBundle\Entity\Clientes:
   constraints:
       - Callback:
           methods:   [isCedulaValida]
#           methods:   [isContratanteValido]
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: email, message: Este email ya esta en uso}
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: cedula, message: Ya existe un cliente con esta cédula}