<?php

namespace MDW\RosantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AseguradorasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AseguradorasRepository extends EntityRepository
{
}
