<?php

namespace MDW\RosantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PolizasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolizasRepository extends EntityRepository
{
    
    
    
    public function listarPolizas()
    {
        $em = $this->getEntityManager();
        $dql = "select p.numero , p.agente 
              from MDWRosantBundle:Polizas p";      
             
             
        $query=$em->createQuery($dql);
        $polizas=$query->getResult();
        return $polizas;      
                
        
            
    }
    
}
