<?php

namespace MDW\RosantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculosRepository extends EntityRepository
{
}
